name: Users Manage CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js version 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Log KEY_PEM secret
        run: echo "KEY_PEM secret value is ${{ secrets.CLIENT_ID }}"

      - name: Create key.pem
        run: echo "${{ secrets.KEY_PEM }}" > key.pem

      - name: Create cert.pem
        run: echo "${{ secrets.CERT_PEM }}" > cert.pem

      - name: Use .env variables
        run: |
          echo "clientID=${{ secrets.CLIENT_ID }}" >> .env

      - name: List files in the directory
        run: ls -al

      - name: Print .env content
        run: cat .env

      - name: Start project with variables
        run: npm start
