name: Users Manage CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js version 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Create key.pem and cert.pem
        run: |
          run: echo "${{ secrets.KEY_PEM }}" > key.pem
          run: echo "${{ secrets.CERT_PEM }}" > cert.pem
      - name: Start project
        run: npm start

