name: Users Manage CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js version 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install

      - name: Log clientID
        run: echo "clientID secret value is ${{ env.KEY_PEM }}"

      - name: Create key.pem
        run: echo "${{ secrets.KEY_PEM }}" > key.pem

      - name: Create cert.pem
        run: echo "${{ secrets.CERT_PEM }}" > cert.pem

      - name: Set clientID environment variable
        run: echo "clientID=${{ env.CLIENT_ID }}" >> $GITHUB_ENV

      - name: Start project
        run: npm start
